# Control your input devices
# See https://wiki.hypr.land/Configuring/Variables/#input
input {
  # Use multiple keyboard layouts and switch between them with Left Alt + Right Alt
  # kb_layout = us,dk,eu
  # kb_layout = us
  kb_layout = us, us

  # dead keys
  kb_variant = ,intl

  # this was the old line (before changing CapsLock to Esc)
  # kb_options = compose:caps # ,grp:alts_toggle
  # new line to chanfe CapsLock to Esc
  kb_options = caps:escape # ,grp:alts_toggle

  # Change speed of keyboard repeat
  repeat_rate = 40
  repeat_delay = 600

  # Start with numlock on by default
  numlock_by_default = true

  # Increase sensitity for mouse/trackpack (default: 0)
  sensitivity = 0.55 # this was commented out by numlock_by_default
  # Add aceleratin (not in the default) 
  accel_profile = adaptative # Makes mouse mouse faster when moving fatester
  #

  touchpad {
    # Use natural (inverse) scrolling
    natural_scroll = true

    # Use two-finger clicks for right-click instead of lower-right corner
    # clickfinger_behavior = true

    # Control the speed of your scrolling
    scroll_factor = 0.7
  }
}



# Scroll nicely in the terminal
windowrule = scrolltouchpad 1.5, class:(Alacritty|kitty)
windowrule = scrolltouchpad 0.2, class:com.mitchellh.ghostty

# Enable touchpad gestures for changing workspaces
# See https://wiki.hyprland.org/Configuring/Gestures/
# gesture = 3, horizontal, workspace
