# Space Is The Place — Monochrome + Neon Lime
# - Pure black background
# - Tmux bar uses ANSI green → neon chartreuse
# - Bold cyan (1;36) renders as white (path + prompt arrow)

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background     = "#000000"  # black
foreground     = "#d9d9d9"  # light gray
dim_foreground = "#808080"  # dim text

[colors.cursor]
text   = "#000000"
cursor = "#d9d9d9"

[colors.selection]
text        = "#000000"
background  = "#3a3a3a"

# ANSI palette
[colors.normal]
black   = "#000000"
red     = "#7a7a7a"
green   = "#84FF00"  # neon chartreuse (tmux status bg)
yellow  = "#a0a0a0"
blue    = "#8e8e8e"
magenta = "#a8a8a8"
cyan    = "#9c9c9c"
white   = "#d9d9d9"

[colors.bright]
black   = "#303030"
red     = "#999999"
green   = "#bcbcbc"
yellow  = "#cfcfcf"
blue    = "#b2b2b2"
magenta = "#d0d0d0"
cyan    = "#FFFFFF"  # bold cyan → white (affects path + ❯)
white   = "#ffffff"
